apiVersion : apps/v1
kind: Deployment
metadata:
  name: ericbinpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ericbinpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: ericbinpipelinesjavascriptdocker 
    spec:
      containers:
        - name: ericbinpipelinesjavascriptdocker 
          image: ericjia.azurecr.io/ericbinpipelinesjavascriptdocker
          ports:
          - containerPort: 8080